// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jhhlktqhrdiashyjgbad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoaGxrdHFocmRpYXNoeWpnYmFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxNjMxNDksImV4cCI6MjA3OTczOTE0OX0.ySmxHjzO0btNFcEqHfBx1b4uBnuU_j6gZQCT8rFzUiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  },
});